StylesPath = styles

MinAlertLevel = suggestion

Packages = MDX

Vocab = ReplicatedTerms, TechJargon, ThirdPartyProducts
# SkippedScopes and IgnoredScopes don't reliably work with MDX
# Use `scope: summary` in individual rules to skip/ignore scopes in MDX files
SkippedScopes = script, style, pre, alt
IgnoredScopes = code, tt, a, img

[formats]
mdx = md

[*.{md,mdx}]

BasedOnStyles = Vale, Replicated

# Disable headings lint until we migrate from title case to sentence case 
Replicated.Headings = NO
Vale.Terms = NO

# Don't lint CLI docs
[docs/reference/kots-cli-*]
BasedOnStyles =

[docs/reference/replicated-cli-*]
BasedOnStyles =

# Don't lint release notes
[docs/release-notes/rn-*]
BasedOnStyles =
