StylesPath = styles

MinAlertLevel = suggestion

Packages = Google, MDX

# Custom vocabularies
Vocab = ReplicatedTerms, TechJargon, ThirdPartyProducts

[formats]
mdx = md

[*.{md,mdx}]
# ^ Applies to Markdown and MDX.

BasedOnStyles = Vale, Google, Replicated

Google.Acronyms = NO
Google.WordList = NO
Google.Colons = NO
Google.Contractions = NO
Google.Headings = NO
Google.Quotes = NO
Vale.Terms = NO

# Don't lint CLI docs
[docs/reference/kots-cli-*]
BasedOnStyles =

[docs/reference/replicated-cli-*]
BasedOnStyles =

# Don't lint release notes
[docs/release-notes/rn-*]
BasedOnStyles =
