module.exports = {
  embeddedClusterSidebar: [
    "embedded-overview",
    "embedded-using",
    "embedded-config",
    "installing-embedded-requirements",
    "installing-embedded",
    "installing-embedded-air-gap",
    "installing-embedded-automation",
    "embedded-manage-nodes",
    "updating-embedded",
    "embedded-troubleshooting",
    {
      type: "category",
      label: "Embedded Cluster Commands",
      items: [
        "embedded-cluster-completion",
        "embedded-cluster-create-join-bundle",
        "embedded-cluster-create-upgrade-bundle",
        "embedded-cluster-enable-ha",
        "embedded-cluster-install",
        "embedded-cluster-node-join",
        "embedded-cluster-node-upgrade",
        "embedded-cluster-remove-node",
        "embedded-cluster-reset",
        "embedded-cluster-shell",
        "embedded-cluster-status",
        "embedded-cluster-support-bundle",
        "embedded-cluster-upgrade",
        "embedded-cluster-version",
      ],
    },
  ],
};
