/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
    // But you can create a sidebar manually
  
    tutorialSidebar: [
  
        'index',
      {
        type: 'category',
        label: 'Support & Troubleshoot',
        items: [
          {
            type: 'category',
            label: 'Preflight Checks',
            items: [
              'preflight/introduction',
              'preflight/cluster-checks',
              'preflight/node-checks',
              'preflight/next-steps'
            ],
          },
          {
            type: 'category',
            label: 'Support Bundle',
            items: [
              'support-bundle/introduction',
              'support-bundle/supportbundle',
              'support-bundle/collecting',
              'support-bundle/discover-cluster-specs'
            ],
          },
          {
            type: 'category',
            label: 'Collect',
            items: [
                'collect/all',
                'collect/ceph',
                'collect/cluster-info',
                'collect/cluster-resources',
                'collect/collectd',
                'collect/collectors',
                'collect/configmap',
                'collect/copy',
                'collect/copy-from-host',
                'collect/data',
                'collect/deprecated/run',
                'collect/exec',
                'collect/http',
                'collect/index',
                'collect/logs',
                'collect/longhorn',
                'collect/mysql',
                'collect/postgresql',
                'collect/redis',
                'collect/registry-images',
                'collect/run-pod',
                'collect/secret',
                'collect/sysctl'
            ],
          },
          {
            type: 'category',
            label: 'Redact',
            items: [
                'redact/index',
                'redact/database-connection-strings',
                'redact/generic-connection-strings',
                'redact/ip-addresses',
                'redact/passwords',
                'redact/redactors',
                'redact/usernames'
            ],
          },
          {
            type: 'category',
            label: 'Analyze',
            items: [
                'analyze/ceph-status',
                'analyze/cluster-pod-statuses',
                'analyze/cluster-version',
                'analyze/configmaps',
                'analyze/container-runtime',
                'analyze/crd',
                'analyze/deployment-status',
                'analyze/distribution',
                'analyze/image-pull-secrets',
                'analyze/index',
                'analyze/ingress',
                'analyze/job-status',
                'analyze/json-compare',
                'analyze/longhorn',
                'analyze/mysql',
                'analyze/node-resources',
                'analyze/outcomes',
                'analyze/postgresql',
                'analyze/regex',
                'analyze/registry-images',
                'analyze/replicaset-status',
                'analyze/secrets',
                'analyze/statefulset-status',
                'analyze/storage-class',
                'analyze/sysctl',
                'analyze/weave-report',
                'analyze/yaml-compare'
            ],
          },
          {
            type: 'category',
            label: 'Host Collect and Analyze',
            items: [
                'host-collect-analyze/all',
                'host-collect-analyze/blockDevices',
                'host-collect-analyze/certificate',
                'host-collect-analyze/cpu',
                'host-collect-analyze/diskUsage',
                'host-collect-analyze/filesystemPerformance',
                'host-collect-analyze/hostOS',
                'host-collect-analyze/hostServices',
                'host-collect-analyze/http',
                'host-collect-analyze/httpLoadBalancer',
                'host-collect-analyze/ipv4Interfaces',
                'host-collect-analyze/memory',
                'host-collect-analyze/overview',
                'host-collect-analyze/run',
                'host-collect-analyze/systemPackages',
                'host-collect-analyze/tcpConnect',
                'host-collect-analyze/tcpLoadBalancer',
                'host-collect-analyze/tcpPortStatus',
                'host-collect-analyze/time'
            ],
          },
        ],
      }]
  };
  
  module.exports = sidebars;
  