/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// Import modular sidebars
const vendorPlatformSidebar = require('./sidebarVendorPlatform');
const enterprisePortalSidebar = require('./sidebarEnterprisePortal');
const securityCenterSidebar = require('./sidebarSecurityCenter');
const compatibilityMatrixSidebar = require('./sidebarCompatibilityMatrix');
const kotsSidebar = require('./sidebarKOTS');
const kurlSidebar = require('./sidebarKURL');
const helmInstallationsSidebar = require('./sidebarHelmInstallations');
const replicatedSdkSidebar = require('./sidebarReplicatedSDK');
const preflightSupportSidebar = require('./sidebarPreflightSupport');

// @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  main: [
    "intro",
    {
      type: "category",
      label: "Release Notes",
      items: [
        "release-notes/rn-whats-new",
        "release-notes/rn-embedded-cluster",
        "release-notes/rn-app-manager",
        "release-notes/rn-kubernetes-installer",
        "release-notes/rn-replicated-sdk",
        "release-notes/rn-vendor-platform",
      ],
    },

    //GET STARTED
    { type: "html", value: "<h5>Get started</h5>", defaultStyle: true },
    "intro-replicated",
    "vendor/kots-faq",
    "vendor/quick-start",
    "vendor/environment-setup",
    "vendor/replicated-onboarding",
    "vendor/replicated-onboarding-helm-only",
    // {
    //   type: 'category',
    //   label: 'Planning',
    //   items: [
    //     'vendor/planning-questionnaire',
    //     'vendor/namespaces',
    //   ],
    // },
    {
      type: "category",
      label: "Tutorials",
      items: [
        "vendor/tutorial-embedded-cluster-automation",
        "vendor/tutorial-helm-cli",
      ],
    },
    {
      type: "category",
      label: "Labs",
      items: [
        {
          type: "link",
          href: "https://play.instruqt.com/embed/replicated/tracks/distributing-with-replicated?token=em_VHOEfNnBgU3auAnN",
          label: "Distributing Your Application with Replicated",
        },
        {
          type: "link",
          href: "https://play.instruqt.com/embed/replicated/tracks/delivering-as-an-appliance?token=em_lUZdcv0LrF6alIa3",
          label: "Delivering Your Application as a Kubernetes Appliance",
        },
        {
          type: "link",
          href: "https://play.instruqt.com/embed/replicated/tracks/avoiding-installation-pitfalls?token=em_gJjtIzzTTtdd5RFG",
          label: "Avoiding Installation Pitfalls",
        },
        {
          type: "link",
          href: "https://play.instruqt.com/embed/replicated/tracks/closing-information-gap?token=em_MO2XXCz3bAgwtEca",
          label: "Closing the Support Information Gap",
        },
        {
          type: "link",
          href: "https://play.instruqt.com/embed/replicated/tracks/protecting-your-assets?token=em_7QjY34G_UHKoREBd",
          label: "Protecting Your Assets",
        },
      ],
    },
    // PRODUCT DOCS
    { type: "html", value: "<h5>Product docs</h5>", defaultStyle: true },
    {
      type: "ref",
      id: "vendor/vendor-portal-creating-account",
      label: "Vendor Platform",
      customProps: {
        sidebar: "vendorPlatformSidebar"
      }
    },
    {
      type: "ref",
      id: "vendor/enterprise-portal-about",
      label: "Enterprise Portal",
      customProps: {
        sidebar: "enterprisePortalSidebar"
      }
    },
    {
      type: "ref",
      id: "vendor/security-center-about",
      label: "Security Center (Alpha)",
      customProps: {
        sidebar: "securityCenterSidebar"
      }
    },
    {
      type: "ref",
      id: "vendor/testing-about",
      label: "Compatibility Matrix",
      customProps: {
        sidebar: "compatibilityMatrixSidebar"
      }
    },
    {
      type: "link",
      href: "/installer/v3/embedded-overview",
      label: "Embedded Cluster",
    },
    {
      type: "ref",
      id: "intro-kots",
      label: "KOTS",
      customProps: {
        sidebar: "kotsSidebar"
      }
    },
    {
      type: "ref",
      id: "vendor/kurl-about",
      label: "kURL",
      customProps: {
        sidebar: "kurlSidebar"
      }
    },
    {
      type: "ref",
      id: "vendor/helm-install-overview",
      label: "Helm Installations with Replicated",
      customProps: {
        sidebar: "helmInstallationsSidebar"
      }
    },
    {
      type: "ref",
      id: "vendor/replicated-sdk-overview",
      label: "Replicated SDK",
      customProps: {
        sidebar: "replicatedSdkSidebar"
      }
    },
    {
      type: "ref",
      id: "vendor/preflight-support-bundle-about",
      label: "Preflight Checks and Support Bundles",
      customProps: {
        sidebar: "preflightSupportSidebar"
      }
    },

    // Reference
    { type: "html", value: "<h5>Reference</h5>", defaultStyle: true },
    {
      type: "category",
      label: "Custom Resources",
      items: [
        "reference/custom-resource-about",
        "reference/custom-resource-application",
        "reference/custom-resource-config",
        "reference/custom-resource-configvalues",
        "reference/custom-resource-helmchart-v2",
        "reference/custom-resource-helmchart",
        "reference/custom-resource-lintconfig",
      ],
    },
    {
      type: "category",
      label: "Replicated Template Functions",
      items: [
        "reference/template-functions-about",
        "reference/template-functions-examples",
        "reference/template-functions-config-context",
        "reference/template-functions-identity-context",
        "reference/template-functions-kurl-context",
        "reference/template-functions-license-context",
        "reference/template-functions-static-context",
      ],
    },
    "reference/cron-expressions",
    "reference/replicated-sdk-apis",
    {
      type: "category",
      label: "Replicated CLI", // This label is generated. Do not edit.
      items: [
        // This list is generated. Do not edit.
        "reference/replicated-cli-installing",
        "reference/replicated",
        "reference/replicated-cli-api",
        "reference/replicated-cli-api-get",
        "reference/replicated-cli-api-patch",
        "reference/replicated-cli-api-post",
        "reference/replicated-cli-api-put",
        "reference/replicated-cli-app",
        "reference/replicated-cli-app-create",
        "reference/replicated-cli-app-hostname",
        "reference/replicated-cli-app-hostname-ls",
        "reference/replicated-cli-app-ls",
        "reference/replicated-cli-app-rm",
        "reference/replicated-cli-channel",
        "reference/replicated-cli-channel-create",
        "reference/replicated-cli-channel-demote",
        "reference/replicated-cli-channel-disable-semantic-versioning",
        "reference/replicated-cli-channel-enable-semantic-versioning",
        "reference/replicated-cli-channel-inspect",
        "reference/replicated-cli-channel-ls",
        "reference/replicated-cli-channel-rm",
        "reference/replicated-cli-channel-un-demote",
        "reference/replicated-cli-cluster",
        "reference/replicated-cli-cluster-addon",
        "reference/replicated-cli-cluster-addon-create",
        "reference/replicated-cli-cluster-addon-create-object-store",
        "reference/replicated-cli-cluster-addon-ls",
        "reference/replicated-cli-cluster-addon-rm",
        "reference/replicated-cli-cluster-create",
        "reference/replicated-cli-cluster-kubeconfig",
        "reference/replicated-cli-cluster-ls",
        "reference/replicated-cli-cluster-nodegroup",
        "reference/replicated-cli-cluster-nodegroup-ls",
        "reference/replicated-cli-cluster-port",
        "reference/replicated-cli-cluster-port-expose",
        "reference/replicated-cli-cluster-port-ls",
        "reference/replicated-cli-cluster-port-rm",
        "reference/replicated-cli-cluster-prepare",
        "reference/replicated-cli-cluster-rm",
        "reference/replicated-cli-cluster-shell",
        "reference/replicated-cli-cluster-update",
        "reference/replicated-cli-cluster-update-nodegroup",
        "reference/replicated-cli-cluster-update-ttl",
        "reference/replicated-cli-cluster-upgrade",
        "reference/replicated-cli-cluster-versions",
        "reference/replicated-cli-completion",
        "reference/replicated-cli-config",
        "reference/replicated-cli-config-init",
        "reference/replicated-cli-customer",
        "reference/replicated-cli-customer-archive",
        "reference/replicated-cli-customer-create",
        "reference/replicated-cli-customer-download-license",
        "reference/replicated-cli-customer-inspect",
        "reference/replicated-cli-customer-ls",
        "reference/replicated-cli-customer-update",
        "reference/replicated-cli-default",
        "reference/replicated-cli-default-clear-all",
        "reference/replicated-cli-default-clear",
        "reference/replicated-cli-default-set",
        "reference/replicated-cli-default-show",
        "reference/replicated-cli-installer",
        "reference/replicated-cli-installer-create",
        "reference/replicated-cli-installer-ls",
        "reference/replicated-cli-instance",
        "reference/replicated-cli-instance-inspect",
        "reference/replicated-cli-instance-ls",
        "reference/replicated-cli-instance-tag",
        "reference/replicated-cli-login",
        "reference/replicated-cli-logout",
        "reference/replicated-cli-network",
        "reference/replicated-cli-network-ls",
        "reference/replicated-cli-network-update",
        "reference/replicated-cli-profile",
        "reference/replicated-cli-profile-add",
        "reference/replicated-cli-profile-edit",
        "reference/replicated-cli-profile-ls",
        "reference/replicated-cli-profile-rm",
        "reference/replicated-cli-profile-set-default",
        "reference/replicated-cli-profile-use",
        "reference/replicated-cli-registry",
        "reference/replicated-cli-registry-add",
        "reference/replicated-cli-registry-add-dockerhub",
        "reference/replicated-cli-registry-add-ecr",
        "reference/replicated-cli-registry-add-gar",
        "reference/replicated-cli-registry-add-gcr",
        "reference/replicated-cli-registry-add-ghcr",
        "reference/replicated-cli-registry-add-other",
        "reference/replicated-cli-registry-add-quay",
        "reference/replicated-cli-registry-ls",
        "reference/replicated-cli-registry-rm",
        "reference/replicated-cli-registry-test",
        "reference/replicated-cli-release",
        "reference/replicated-cli-release-compatibility",
        "reference/replicated-cli-release-create",
        "reference/replicated-cli-release-download",
        "reference/replicated-cli-release-image",
        "reference/replicated-cli-release-image-ls",
        "reference/replicated-cli-release-inspect",
        "reference/replicated-cli-release-lint",
        "reference/replicated-cli-release-ls",
        "reference/replicated-cli-release-promote",
        "reference/replicated-cli-release-test",
        "reference/replicated-cli-release-update",
        "reference/replicated-cli-version",
        "reference/replicated-cli-version-upgrade",
        "reference/replicated-cli-vm",
        "reference/replicated-cli-vm-create",
        "reference/replicated-cli-vm-ls",
        "reference/replicated-cli-vm-port",
        "reference/replicated-cli-vm-port-expose",
        "reference/replicated-cli-vm-port-ls",
        "reference/replicated-cli-vm-port-rm",
        "reference/replicated-cli-vm-rm",
        "reference/replicated-cli-vm-scp-endpoint",
        "reference/replicated-cli-vm-ssh-endpoint",
        "reference/replicated-cli-vm-update",
        "reference/replicated-cli-vm-update-ttl",
        "reference/replicated-cli-vm-versions",
      ],
    },
    {
      type: "category",
      label: "KOTS CLI",
      items: [
        "reference/kots-cli-getting-started",
        "reference/kots-cli-global-flags",
        {
          type: "category",
          label: "admin-console",
          items: [
            "reference/kots-cli-admin-console-index",
            "reference/kots-cli-admin-console-garbage-collect-images",
            "reference/kots-cli-admin-console-generate-manifests",
            "reference/kots-cli-admin-console-push-images",
            "reference/kots-cli-admin-console-upgrade",
          ],
        },
        {
          type: "category",
          label: "backup",
          items: [
            "reference/kots-cli-backup-index",
            "reference/kots-cli-backup-ls",
          ],
        },
        {
          type: "category",
          label: "docker",
          items: [
            "reference/kots-cli-docker-index",
            "reference/kots-cli-docker-ensure-secret",
          ],
        },
        "reference/kots-cli-download",
        "reference/kots-cli-enable-ha",
        {
          type: "category",
          label: "get",
          items: [
            "reference/kots-cli-get-index",
            "reference/kots-cli-get-apps",
            "reference/kots-cli-get-backups",
            "reference/kots-cli-get-config",
            "reference/kots-cli-get-restores",
            "reference/kots-cli-get-versions",
          ],
        },
        {
          type: "category",
          label: "identity-service",
          items: [
            "reference/kots-cli-identity-service-index",
            "reference/kots-cli-identity-service-enable-shared-password",
          ],
        },
        "reference/kots-cli-install",
        "reference/kots-cli-pull",
        "reference/kots-cli-remove",
        "reference/kots-cli-reset-password",
        "reference/kots-cli-reset-tls",
        {
          type: "category",
          label: "restore",
          items: [
            "reference/kots-cli-restore-index",
            "reference/kots-cli-restore-ls",
          ],
        },
        {
          type: "category",
          label: "set",
          items: [
            "reference/kots-cli-set-index",
            "reference/kots-cli-set-config",
          ],
        },
        "reference/kots-cli-upload",
        {
          type: "category",
          label: "upstream",
          items: [
            "reference/kots-cli-upstream",
            "reference/kots-cli-upstream-download",
            "reference/kots-cli-upstream-upgrade",
          ],
        },
        {
          type: "category",
          label: "velero",
          items: [
            "reference/kots-cli-velero-configure-aws-s3",
            "reference/kots-cli-velero-configure-azure",
            "reference/kots-cli-velero-configure-gcp",
            "reference/kots-cli-velero-configure-hostpath",
            "reference/kots-cli-velero-configure-internal",
            "reference/kots-cli-velero-configure-nfs",
            "reference/kots-cli-velero-configure-other-s3",
            "reference/kots-cli-velero-ensure-permissions",
            "reference/kots-cli-velero-index",
            "reference/kots-cli-velero-print-fs-instructions",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Vendor API v3",
      items: [
        {
          type: "doc",
          id: "reference/vendor-api-using",
        },
        {
          type: "link",
          label: "Vendor API v3 Documentation",
          href: "https://replicated-vendor-api.readme.io/v3/",
        },
      ],
    },

    //OPEN SOURCE DOCS
    { type: "html", value: "<h5>Open source docs</h5>", defaultStyle: true },
    {
      type: "link",
      href: "https://kurl.sh/docs/introduction/",
      label: "kURL.sh",
    },
    {
      type: "link",
      href: "https://troubleshoot.sh/docs/collect/",
      label: "Troubleshoot.sh",
    },

    // POLICIES
    { type: "html", value: "<h5>Platform overview</h5>", defaultStyle: true },
    {
      type: "category",
      label: "Replicated Policies",
      items: [
        "vendor/policies-vulnerability-patch",
        "vendor/policies-support-lifecycle",
        "vendor/policies-data-transmission",
        "vendor/policies-infrastructure-and-subprocessors",
      ],
    },
    {
      type: "category",
      label: "Replicated Data Storage",
      items: ["vendor/data-availability", "vendor/offsite-backup"],
    },
    {
      type: "category",
      label: "Security at Replicated",
      items: [
        {
          type: "link",
          label: "Trust Center",
          href: "https://trust.replicated.com/",
        },
        {
          type: "link",
          label: "Status Page",
          href: "https://status.replicated.com/",
        },
        {
          type: "link",
          label: "Security at Replicated",
          href: "https://www.replicated.com/security/",
        },
        "enterprise/sbom-validating",
        "vendor/vendor-password-integrity",
        "vendor/replicated-sdk-slsa-validating",
      ],
    },
  ],
  
  // Product-specific sidebars
  ...vendorPlatformSidebar,
  ...enterprisePortalSidebar,
  ...securityCenterSidebar,
  ...compatibilityMatrixSidebar,
  ...kotsSidebar,
  ...kurlSidebar,
  ...helmInstallationsSidebar,
  ...replicatedSdkSidebar,
  ...preflightSupportSidebar,
};

module.exports = sidebars;
