#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

# Resolve latest once so the source checkout and PR title refer to the same release.
version="$(gh api repos/replicatedhq/replicated/releases/latest --jq .tag_name)"
source_dir="$tmp_dir/replicated"
git init --quiet "$source_dir"
git -C "$source_dir" remote add origin https://github.com/replicatedhq/replicated.git
git -C "$source_dir" fetch --depth 1 origin "refs/tags/$version"
git -C "$source_dir" checkout --quiet --detach FETCH_HEAD
(
  cd "$source_dir"
  CGO_ENABLED=0 go run \
    -tags "containers_image_ostree_stub exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp" \
    ./docs/gen.go
)
node scripts/ci/update-replicated-cli-docs.cjs "$source_dir/gen/docs"

paths=(sidebars.js docs/reference/replicated.mdx 'docs/reference/replicated-cli-*.mdx')
if [[ -z "$(git status --porcelain -- "${paths[@]}")" ]]; then
  echo "CLI documentation is already up to date for $version."
  exit 0
fi

if [[ "${DRY_RUN:-false}" == "true" || "${DRY_RUN:-false}" == "1" ]]; then
  echo "Dry run: CLI documentation changes for $version follow."
  git --no-pager diff -- "${paths[@]}"
  # git diff does not include newly generated, untracked pages.
  while IFS= read -r -d '' file; do
    git --no-pager diff --no-index -- /dev/null "$file" || [[ $? == 1 ]]
  done < <(git ls-files --others --exclude-standard -z -- "${paths[@]}")
  exit 0
fi

: "${GH_TOKEN:?GH_TOKEN is required to create the CLI documentation PR}"
branch="automation/replicated-cli-docs"
title="Update Replicated CLI docs for $version"
target_repo="${GITHUB_REPOSITORY:-replicatedhq/replicated-docs}"
git config user.name replicated-ci
git config user.email replicated-ci@users.noreply.github.com
git switch -C "$branch"
git add -- "${paths[@]}"
git commit -m "$title"

remote_sha="$(git ls-remote --heads origin "refs/heads/$branch" | awk '{print $1}')"
if [[ -n "$remote_sha" ]]; then
  git push --force-with-lease="refs/heads/$branch:$remote_sha" origin "HEAD:refs/heads/$branch"
else
  git push origin "HEAD:refs/heads/$branch"
fi

cat > "$tmp_dir/pr-body.md" <<EOF
Regenerate the CLI reference pages and sidebar using Replicated CLI $version.

Generated by the [CLI docs workflow](https://github.com/replicatedhq/replicated-docs/blob/main/.depot/workflows/replicated-cli-docs.yml).
EOF
pr_url="$(gh pr list --repo "$target_repo" --head "$branch" --base main --state open --json url --jq '.[0].url // empty')"
if [[ -z "$pr_url" ]]; then
  pr_url="$(gh pr create --repo "$target_repo" --base main --head "$branch" --title "$title" --body-file "$tmp_dir/pr-body.md")"
else
  gh pr edit "$pr_url" --repo "$target_repo" --title "$title" --body-file "$tmp_dir/pr-body.md"
fi
echo "CLI documentation PR: $pr_url"
